# Generated by Django 6.0.5 on 2026-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('total_games', models.IntegerField(default=0)),
                ('games_consumed', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('beginner_games', models.IntegerField(default=0)),
                ('easy_games', models.IntegerField(default=0)),
                ('medium_games', models.IntegerField(default=0)),
                ('hard_games', models.IntegerField(default=0)),
                ('expert_games', models.IntegerField(default=0)),
                ('beginner_total_score', models.FloatField(default=0)),
                ('easy_total_score', models.FloatField(default=0)),
                ('medium_total_score', models.FloatField(default=0)),
                ('hard_total_score', models.FloatField(default=0)),
                ('expert_total_score', models.FloatField(default=0)),
                ('beginner_max_score', models.FloatField(default=0)),
                ('easy_max_score', models.FloatField(default=0)),
                ('medium_max_score', models.FloatField(default=0)),
                ('hard_max_score', models.FloatField(default=0)),
                ('expert_max_score', models.FloatField(default=0)),
                ('paid_game_limit', models.IntegerField(default=100)),
            ],
        ),
    ]
