# Generated by Django 6.0.5 on 2026-05-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='total_ai_cost',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('animal', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('won', models.BooleanField()),
                ('ai_cost', models.FloatField()),
                ('questions_used', models.IntegerField()),
                ('wrong_tries', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
