# Generated by Django 6.0.5 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playerprofile_total_ai_cost_gamehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='paid_game_limit',
            new_name='remaining_games',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='beginner_max_score',
            new_name='total_average_score',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='beginner_games',
            new_name='total_games_played',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='beginner_total_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='easy_games',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='easy_max_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='easy_total_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='expert_games',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='expert_max_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='expert_total_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='games_consumed',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='hard_games',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='hard_max_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='hard_total_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='medium_games',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='medium_max_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='medium_total_score',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='total_games',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='total_score',
        ),
    ]
