# Generated by Django 6.0.5 on 2026-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_levelstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelstatistics',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
