# Generated by Django 6.0.5 on 2026-05-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_levelstatistics_average_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LevelStatistics',
            new_name='LevelStats',
        ),
    ]
