# Generated by Django 6.0.5 on 2026-05-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_levelstatistics_levelstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
